server:
  port: 8088 #服务器启动端口
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #配置数据源的类型・
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  application:
    name: uniappshopping
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: shopping.uniappshopping.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #在控制台打印sql
